name: Run npm build

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Run `npm install` `npm build`          
        run: |
          npm install
          npm run build
